import anthropic
import os
import json
import requests
import base64
from message_bus import send_message, get_messages
from dotenv import load_dotenv

load_dotenv()

client = anthropic.Anthropic(api_key=os.environ['ANTHROPIC_API_KEY'])
GITHUB_TOKEN = os.environ['GITHUB_TOKEN']
REPO = os.environ['GITHUB_REPO']
HEADERS = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
}


def call_llm(system_prompt, user_prompt):
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=2000,
        system=system_prompt,
        messages=[{"role": "user", "content": user_prompt}]
    )
    return response.content[0].text


def get_main_sha():
    r = requests.get(
        f'https://api.github.com/repos/{REPO}/git/ref/heads/main',
        headers=HEADERS
    )
    return r.json()["object"]["sha"]


def run_engineer():
    print("\n⚙️ Engineer Agent waiting for task...")
    messages = get_messages("engineer")
    if not messages:
        print("No messages for Engineer Agent.")
        return None, None

    msg = messages[0]
    spec = msg["payload"]["spec"]
    parent_id = msg["message_id"]

    print("⚙️ Engineer Agent generating HTML landing page...")

    # Generate HTML with LLM
    html = call_llm(
        system_prompt="You are a frontend developer. Return ONLY raw HTML code, no markdown, no explanation.",
        user_prompt=f'''
        Create a beautiful, modern HTML landing page for this startup:
        Value Proposition: {spec["value_proposition"]}
        Features: {json.dumps(spec["features"])}
        Personas: {json.dumps(spec["personas"])}

        Include:
        - A compelling hero section with headline and subheadline
        - A features section showcasing all features
        - A call-to-action button
        - Inline CSS for a clean, professional design
        - Responsive layout
        Make it visually impressive with a dark gradient header.
        '''
    )

    print("⚙️ Engineer creating GitHub branch, committing file, opening PR...")

    # Create branch
    branch = "agent-landing-page"
    sha = get_main_sha()

    branch_res = requests.post(
        f'https://api.github.com/repos/{REPO}/git/refs',
        headers=HEADERS,
        json={"ref": f"refs/heads/{branch}", "sha": sha}
    )
    print(f"  Branch creation: {branch_res.status_code}")

    # Commit HTML file
    content_b64 = base64.b64encode(html.encode()).decode()
    commit_res = requests.put(
        f'https://api.github.com/repos/{REPO}/contents/index.html',
        headers=HEADERS,
        json={
            "message": "feat: Add AI-generated landing page",
            "content": content_b64,
            "branch": branch,
            "author": {"name": "EngineerAgent", "email": "agent@launchmind.ai"}
        }
    )
    print(f"  Commit: {commit_res.status_code}")

    # Create issue
    issue_res = requests.post(
        f'https://api.github.com/repos/{REPO}/issues',
        headers=HEADERS,
        json={
            "title": "Initial landing page creation",
            "body": f"Create landing page for: {spec['value_proposition']}\n\nFeatures to highlight:\n" +
                    "\n".join([f"- {f['name']}: {f['description']}" for f in spec['features']])
        }
    )
    issue_url = issue_res.json().get("html_url", "N/A")
    print(f"  Issue created: {issue_url}")

    # Open Pull Request
    pr_res = requests.post(
        f'https://api.github.com/repos/{REPO}/pulls',
        headers=HEADERS,
        json={
            "title": "feat: AI-generated landing page",
            "body": f"Landing page for: {spec['value_proposition']}\n\nGenerated by EngineerAgent 🤖",
            "head": branch,
            "base": "main"
        }
    )
    pr_url = pr_res.json().get("html_url", "N/A")
    print(f"✅ Engineer done! PR: {pr_url}")

    send_message("engineer", "ceo", "result", {
        "pr_url": pr_url,
        "issue_url": issue_url,
        "html": html
    }, parent_id)

    return pr_url, issue_url
